INSERT INTO Authors (FirstName, LastName)
VALUES
('Jaideva', 'Goswami'),
('John', 'Foreman'),
('Stephen', 'Hawking'),
('Stephen', 'Dubner'),
('Edward', 'Said'),
('Vladimir', 'Vapnik'),
('V P', 'Menon'),
('Leonard', 'Mlodinow'),
('Frank', 'Shih'),
('Maria', 'Konnikova'),
('Sebastian', 'Gutierrez'),
('Kurt', 'Vonnegut'),
('Cedric', 'Villani'),
('Gerald', 'Sussman'),
('Abraham', 'Eraly'),
('Frank', 'Kafka'),
('John', 'Pratt'),
('Robert', 'Nisbet'),
('H. G.', 'Wells'),
('Werner', 'Heisenberg'),
('Andy', 'Oram'),
('Terence', 'Tao'),
('Drew', 'Conway'),
('Nate', 'Silver'),
('Wes', 'McKinney'),
('Thomas', 'Cormen'),
('Siddhartha', 'Deb'),
('Albert', 'Camus'),
('Arthur Conan', 'Doyle'),
('Adam', 'Smith'),
('Ken', 'Follett'),
('Adolf', 'Hitler'),
('Fritjof', 'Capra'),
('Richard', 'Feynman'),
('Ernest', 'Hemingway'),
('Frederick', 'Forsyth'),
('Jeffery', 'Archer'),
('Randy', 'Pausch'),
('Ayn', 'Rand'),
('Michael', 'Crichton'),
('John', 'Steinbeck'),
('Edgar Allen', 'Poe'),
('Will', 'Durant'),
('P L', 'Deshpande'),
('John', 'Grisham'),
('V. S.', 'Naipaul'),
('Joseph', 'Heller'),
('Bob', 'Dylan'),
('Madan', 'Gupta'),
('Alfred', 'Stonier'),
('W. H.', 'Greene'),
('Gary', 'Bradsky'),
('Andrew', 'Tanenbaum'),
('David', 'Forsyth'),
('Schilling', 'Taub'),
('Yashwant', 'Kanetkar'),
('Jonathan', 'Stroud'),
('Fyodor', 'Dostoevsky'),
('Dan', 'Brown'),
('Amartya', 'Sen'),
('Amitav', 'Ghosh'),
('Lorraine', 'Hansberry'),
('Bob', 'Woodward'),
('Kuldip', 'Nayar'),
('Sunita', 'Deshpande'),
('William', 'Dalrymple'),
('Sanjay', 'Garg'),
('V P', 'Kale'),
('Shashi', 'Tharoor'),
('Dominique', 'Lapierre'),
('Bertrand', 'Russell'),
('Sam', 'Harris'),
('Earle Stanley', 'Gardner'),
('Peter', 'Drucker'),
('David', 'Bodanis'),
('Victor', 'Hugo'),
('Richard', 'Gordon'),
('George', 'Orwell'),
('Lee', 'Iacoca'),
('William S', 'Maugham'),
('Robert', 'Pirsig'),
('Robert', 'Fisk'),
('Amir', 'Aczel'),
('Samuel', 'Huntington'),
('Richard', 'Bach'),
('Jawaharlal', 'Nehru'),
('Gerald', 'Durrell'),
('Simon', 'Singh'),
('Hart', 'Duda'),
('Thomas', 'Friedman'),
('Keith', 'Devlin'),
('James', 'Gleick'),
('Joy', 'Thomas'),
('Muhammad', 'Rashid'),
('Ned', 'Mohan'),
('Simon', 'Haykin'),
('Vladimir', 'Vapnik'),
('Alex', 'Rutherford'),
('Michael', 'Baz-Zohar'),
('Jim', 'Corbett'),
('Jules', 'Verne'),
('Eric', 'Raymond'),
('Sergio', 'Franco'),
('Allen', 'Downey'),
('Morris', 'West'),
('Phillip', 'Janert'),
('Carl', 'Sagan'),
('E T', 'Bell'),
('Richard', 'Dawkins'),
('Sudhanshu', 'Ranjan'),
('Kautiyla', NULL),
('Palkhivala', NULL),
('Sorabjee', NULL),
('Hussain', 'Zaidi'),
('Peter', 'Ackroyd'),
('Nariman', NULL),
('Jean', 'Sassoon'),
('Peter', 'Dickinson'),
('Machiavelli', NULL),
('Aldous', 'Huxley'),
('J K', 'Rowling'),
('Steig', 'Larsson'),
('Steve', 'Eddins'),
('Charles', 'Dickens');
