INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Fundamentals of WavAuthor_IDelets',1,1);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Data Smart',2,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('God Created the Integers',3,3);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Superfreakonomics',4,4);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Orientalism',5,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Nature of Statistical Learning Theory, The',6,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Integration of the Indian States',7,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Drunkard''s Walk, The',8,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Image Processing & Mathematical Morphology',9,1);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('How to Think Like Sherlock Holmes',10,7);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Data Scientists at Work',11,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Slaughterhouse Five',12,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Birth of a Theorem',13,3);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Structure & Interpretation of Computer Programs',14,9);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Age of Wrath, The',15,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Trial, The',16,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Statistical Decision Theory''',17,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Data Mining Handbook',18,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('New Machiavelli, The',19,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Physics & Philosophy',20,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Making Software',21,9);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Analysis, Vol I',22,3);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Machine Learning for Hackers',23,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Signal and the Noise, The',24,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Python for Data Analysis',25,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Introduction to Algorithms',26,9);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Beautiful and the Damned, The',27,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Outsider, The',28,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Complete Sherlock Holmes, The - Vol I',29,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Complete Sherlock Holmes, The - Vol II',29,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Wealth of Nations, The',30,4);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Pillars of the Earth, The',31,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Mein Kampf',32,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Tao of Physics, The',33,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Surely You''re Joking Mr Feynman',34,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Farewell to Arms, A',35,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Veteran, The',36,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('False Impressions',37,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Last Lecture, The',38,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Return of the Primitive',39,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Jurassic Park',40,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Russian Journal, A',41,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Tales of Mystery and Imagination',42,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Freakonomics',4,4);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Hidden Connections, The',33,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Story of Philosophy, The',43,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Asami Asami',44,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Journal of a Novel',41,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Once There Was a War',41,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Moon is Down, The',41,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Brethren, The',45,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('In a Free State',46,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Catch 22',47,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Dylan on Dylan',48,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Soft Computing & Intelligent Systems',49,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Textbook of Economic Theory',50,4);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Econometric Analysis',51,4);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Learning OpenCV',52,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Data Structures Using C & C++',53,9);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Computer Vision, A Modern Approach',54,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Principles of Communication Systems',55,9);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Let Us C',56,9);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Amulet of Samarkand, The',57,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Crime and Punishment',58,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Angels & Demons',59,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Argumentative Indian, The',60,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Sea of Poppies',61,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Idea of Justice, The',60,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Raisin in the Sun, A',62,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('All the President''s Men',63,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Prisoner of Birth, A',37,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Scoop!',64,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Ahe Manohar Tari',65,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Last Mughal, The',66,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Radiowaril Bhashane & Shrutika',44,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Gun Gayin Awadi',44,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Aghal Paghal',44,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Maqta-e-Ghalib',67,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Manasa',68,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('India from Midnight to Milennium',69,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Great Indian Novel, The',69,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('O Jerusalem!',70,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('City of Joy, The',70,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Freedom at Midnight',70,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Winter of Our Discontent, The',41,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('On Education',71,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Free Will',72,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Bookless in Baghdad',69,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Case of the Lame Canary, The',73,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Theory of Everything, The',3,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('New Markets & Other Essays',74,4);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Electric Universe',75,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Hunchback of Notre Dame, The',76,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Burning Bright',41,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Age of Discontuinity, The',74,4);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Doctor in the Nude',77,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Down and Out in Paris & London',78,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Identity & Violence',60,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Beyond the Three Seas',66,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Talking Straight',79,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Maugham''s Collected Short Stories, Vol 3',80,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Phantom of Manhattan, The',36,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Ashenden of The British Agent',80,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Zen & The Art of Motorcycle Maintenance',81,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Great War for Civilization, The',82,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('We the Living',39,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Artist and the Mathematician, The',83,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('History of Western Philosophy',71,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Rationality & Freedom',60,4);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Clash of Civilizations and Remaking of the World Order',87,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Uncommon Wisdom',33,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Half A Life',46,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Discovery of India, The',86,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Apulki',44,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Unpopular Essays',71,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Deceiver, The',36,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Veil: Secret Wars of the CIA',63,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Char Shabda',44,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Rosy is My Relative',87,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Moon and Sixpence, The',80,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Short History of the World, A',19,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Trembling of a Leaf, The',80,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Doctor on the Brain',77,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Simpsons & Their Mathematical Secrets',88,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Pattern Classification',89,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('From Beirut to Jerusalem',90,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Code Book, The',88,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Age of the Warrior, The',82,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Numbers Behind Numb3rs, The',91,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Life in Letters, A',41,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Information, The',92,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Elements of Information Theory',93,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Power Electronics - Rashid',94,9);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Power Electronics - Mohan',95,9);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Neural Networks',96,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Grapes of Wrath, The',41,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Vyakti ani Valli',44,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Statistical Learning Theory',97,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Empire of the Mughal - The Tainted Throne',98,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Empire of the Mughal - Brothers at War',98,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Empire of the Mughal - Ruler of the World',98,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Empire of the Mughal - The Serpent''s Tooth',98,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Empire of the Mughal - Raiders from the North',98,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Mossad',99,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Jim Corbett Omnibus',10,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('20000 Leagues Under the Sea',101,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Batatyachi Chal',44,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Hafasavnuk',44,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Urlasurla',44,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Pointers in C',56,9);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Cathedral and the Bazaar, The',102,9);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Design with OpAmps',103,9);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Think Complexity',104,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Devil''s Advocate, The',105,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Ayn Rand Answers',39,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Philosophy: Who Needs It',39,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Data Analysis with Open Source Tools',106,2);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Broca''s Brain',107,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Men of Mathematics',108,3);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Oxford book of Modern Science Writing',109,6);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Justice, Judiciary and Democracy',110,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Arthashastra, The',111,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('We the People',112,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('We the Nation',112,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Courtroom Genius, The',113,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Dongri to Dubai',114,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('History of England, Foundation',115,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('City of Djinns',66,5);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('India''s Legal System',116,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('More Tears to Cry',117,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Ropemaker, The',118,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Angels & Demons',59,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Prince, The',119,11);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Eyeless in Gaza',120,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Tales of Beedle the Bard',121,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Girl with the Dragon Tattoo',122,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Girl who kicked the Hornet''s Nest',122,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Girl who played with Fire',122,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Batman Handbook',NULL,12);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Murphy''s Law',NULL,10);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Structure and Randomness',22,3);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Image Processing with MATLAB',123,1);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Animal Farm',78,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Idiot, The',58,8);
INSERT INTO Books(Title,Author_ID,Genre_ID) VALUES ('Christmas Carol, A',124,8);
